name: release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    concurrency:
      group: release
      cancel-in-progress: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Generate Changelog
        id: get_changelog
        run: |
          tag="$(git --no-pager tag --sort=creatordate --merged ${{ github.ref_name }} | tail -1)"
          limit="-1"
          if [ -n "$tag" ]; then
            limit="$tag..HEAD"
          fi
          changelog="$(echo -ne "$(git log "$limit" --pretty=format:'- %s')")"
          changelog="$(echo "$changelog" | sed 's/$/  /')"
          {
            echo 'changelog<<EOF'
            echo "$changelog"
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - name: Extract Version
        id: get_version
        run: echo "version=$(<VERSION)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: ${{ steps.get_version.outputs.version }}
          prerelease: false
          body: ${{ steps.get_changelog.outputs.changelog }}
